- components/job/section-types/TitleAndList/TitleAndList.styles.js
- ссылка на jira: COM-2109
- стенд: http://fix-com-2109.csssr.cloud/
> fix: COM-2109 Уменьшил отступы для страницы вакансий

- utils/withError.js
- ссылка на jira: COM-2037
- стенд: http://COM-2037.csssr.cloud/
> fix(jobs): COM-2037 fix job page error handling

- components/express/Calculator/CalculatorForm/CalculatorForm.styles.js
- ссылка на jira: COM-2093
- стенд: http://fix-com-2093.csssr.cloud/
> fix: COM-2093 Ограничил ширину textarea для страницы Express

- static/locales/en/common.json
- static/locales/en/main.json
- ссылка на jira: COM-2110
- стенд: http://fix-com-2110.csssr.cloud/
> fix: COM-2110 Обновил тексты на главной en

- components/Head.jsx
- components/jobs-faq/JobsFaqPage.jsx
- ссылка на jira: COM-2129
- стенд: http://COM-2129.csssr.cloud/
> fix(SEO): COM-2129 fix canonical links for jobs pages

- utils/validators/required.js
- ссылка на jira: COM-2091
- стенд: http://fix-com-2091.csssr.cloud/
> fix: COM-2091 Добавил валидацию пробелов в обязательных полях

- components/job/CandidateForm/CandidateForm.jsx
- ссылка на jira: COM-2092
- стенд: http://fix-com-2092.csssr.cloud/
> fix: COM-2092 Сброс состояния ошибки при переходе на новую вакансию

- .env.development
- components/Header/Header.jsx
- ссылка на jira: COM-2112
- стенд: http://COM-2112.csssr.cloud/
> COM-2112: add .env.development to simplify app start; add ab test for header

- components/ui-kit/Checkbox/Checkbox.styles.js
- ссылка на jira: COM-2135
- стенд: http://feat-com-2135.csssr.cloud/
> COM-2135: Поменял цвет чекбокса при ошибке

- components/Layout/Layout.jsx
- pages/_app.js
- ссылка на jira: COM-2128
- стенд: http://fix-com-2128.csssr.cloud/
> fix: COM-2128 Migrated global styles in _app

- components/Header/Menu/Nav/Nav.jsx
- ссылка на jira: COM-2145
- стенд: http://fix-com-2145.csssr.cloud/
> fix: COM-2145 Поправил data-testid в nav-dropdown 

- components/express/Calculator/Calculator.jsx
- components/express/Calculator/CalculatorForm/CalculatorForm.jsx
- components/express/Calculator/CalculatorForm/DropdownButton/DropdownButton.jsx
- components/express/Calculator/CalculatorForm/Note/Note.jsx
- components/express/Greeting/Greeting.jsx
- static/locales/en/express.json
- ссылка на jira: COM-2156
- стенд: http://fix-sch-2156.csssr.cloud/
> fix: SCH-2156 Добавил data-testid на страницу EXPRESS

- .github/workflows/update-e2e-tools.yaml
- e2e-tests/.eslintrc.js
- e2e-tests/.npmrc
- e2e-tests/nightwatch/.eslintrc.js
- e2e-tests/nightwatch/Jenkinsfile
- e2e-tests/nightwatch/tests/00 Header/01 Роуты для RU.test.js
- e2e-tests/nightwatch/tests/00 Header/02 Роуты для EN.test.js
- e2e-tests/nightwatch/tests/00 Header/03 Скриншоты хеддера RU.test.js
- e2e-tests/nightwatch/tests/00 Header/04 Скриншоты хеддера EN.test.js
- e2e-tests/nightwatch/tests/01 Main/01 Редиректы главной.test.js
- e2e-tests/nightwatch/tests/01 Main/02 Оправка заявок с главной.test.js
- e2e-tests/nightwatch/tests/02 Express/01 Редиректы Express.test.js
- e2e-tests/nightwatch/tests/03 MVP/01 Редиректы MVP.test.js
- e2e-tests/nightwatch/tests/06 Fintech/01 Отправка заявок с Финтех.test.js
- e2e-tests/nightwatch/tests/06 Fintech/02 Скриншоты.test.js
- e2e-tests/nightwatch/tests/07 IT companies/01 Отправка заявок с ИТ.test.js
- e2e-tests/nightwatch/tests/07 IT companies/02 Скриншоты.test.js
- e2e-tests/nightwatch/tests/08 E-Commerce/01 Отправка заявок с E-commerce.test.js
- e2e-tests/nightwatch/tests/08 E-Commerce/02 Скриншоты.test.js
- e2e-tests/nightwatch/tests/09 Media and marketing/01 Отправка заявок с Медиа&Маркетинг.test.js
- e2e-tests/nightwatch/tests/09 Media and marketing/02 Скриншоты.test.js
- e2e-tests/nightwatch/tests/10 Core Values/01 Отправка заявок.test.js
- e2e-tests/nightwatch/tests/10 Core Values/02 Скриншоты.test.js
- e2e-tests/nightwatch/tests/15 LMS/01 Redirects LMS.test.js
- e2e-tests/nightwatch/tests/actions/modalContInfo.js
- e2e-tests/package.json
- e2e-tests/yarn.lock
- ссылка на jira: https://jira.csssr.io/browse/COM-2127
- стенд: https://csssr.com/
Обновил пакеты для утилиты и внес правки в некоторых шагах и оформлении. 
* скриншоты
> COM-2127:E2E тесты_косметические правки

- static/locales/en/industry.json
- static/locales/en/project.json
- static/locales/ru/project.json
- ссылка на jira: https://jira.csssr.io/browse/COM-2185
https://jira.csssr.io/browse/COM-2186
https://jira.csssr.io/browse/COM-2189
https://jira.csssr.io/browse/COM-2190
- стенд: http://fix-com-2185.csssr.cloud/
> fix: COM-2185 Правки на странице QMarketing

- components/project/TechStack/TechStack.styles.js
- ссылка на jira: https://jira.csssr.io/browse/COM-2188
- стенд: http://fix-com-2188.csssr.cloud/
> fix: COM-2188 Исправил положение волнистой линии

- components/project/AboutProject/AboutProject.jsx
- ссылка на jira: https://jira.csssr.io/browse/COM-2227
- стенд: http://fix-com-2227.csssr.cloud/
> fix: COM-2227 Исправил верстку на проектах

- static/locales/ru/project.json
- ссылка на jira: https://jira.csssr.io/browse/COM-2228
- стенд: http://fix-com-2228.csssr.cloud/
> fix: COM-2228 Projects|  Убрал заглавную букву в месяце

- components/Header/Header.jsx
- components/contact-us/ContactUs/Map/Map.jsx
- data/headerLinks.js
- static/locales/en/common.json
- static/locales/ru/common.json
- ссылка на jira: COM-2177
- стенд: http://feat-com-2177.csssr.cloud/
> COM-2177: Правки хэдера

- components/project/TechStack/TechStack.styles.js
- ссылка на jira: https://jira.csssr.io/browse/COM-2188
- стенд: http://fix-com-2188.csssr.cloud/
> fix: COM-2188 Tablet| Исправил отображение волнистой линни

- components/project/TechStack/TechStack.styles.js
- static/icons/project/techStack/duration/curvy-line.svg
- ссылка на jira: https://jira.csssr.io/browse/COM-2244
- стенд: http://fix-com-2244.csssr.cloud/
> fix: COM-2244 360| Исправил стыки у волнистой линии

- components/project/TechStack/TechStack.styles.js
- ссылка на jira: https://jira.csssr.io/browse/COM-2245
- стенд: http://fix-com-2245.csssr.cloud/
> fix: COM-2245 360| Исправил обрезание скобки

- static/locales/en/project.json
- static/locales/ru/project.json
- ссылка на jira: https://jira.csssr.io/browse/COM-2242
- стенд: http://fix-com-2242.csssr.cloud/
> fix: COM-2242 Mindbox\  Исправил тайтл в блоке about

- components/project/AboutProject/AboutProject.styles.js
- ссылка на jira: https://jira.csssr.io/browse/COM-2196
- стенд: http://fix-com-2196.csssr.cloud/
> fix: COM-2196 Исправил отступы на странице mindbox

- components/ContactButton.jsx
- components/Layout/Layout.jsx
- components/industry/CoreValues/CoreValues.jsx
- components/industry/Greeting/Greeting.jsx
- components/industry/Greeting/Greeting.styles.js
- components/industry/Projects/Projects.jsx
- components/industry/ProjectsItem/ProjectsItem.jsx
- data/industry/projects/index.js
- ссылка на jira: COM-2123
- стенд: http://com-2123.csssr.cloud/
> COM-2123: Добавил data-testid на страницы Индустрий

- components/project/AboutProject/AboutProject.styles.js
- ссылка на jira: https://jira.csssr.io/browse/COM-2266
- стенд: http://fix-com-2266.csssr.cloud/
> fix: COM-2266 Исправил font-weight в блоке About project

- components/project/AboutProject/AboutProject.styles.js
- ссылка на jira: https://jira.csssr.io/browse/COM-2262
- стенд: http://fix-com-2262.csssr.cloud/
> fix: COM-2265 Исправил положение картинки на Mindbox

- static/locales/en/industry.json
- static/locales/ru/industry.json
- ссылка на jira: https://jira.csssr.io/browse/COM-2265
- стенд: http://fix-com-2265.csssr.cloud/
> fix: COM-2265 Добавил второй проект в заголовок на странице индустрий

- components/project/AboutProject/AboutProject.styles.js
- ссылка на jira: https://jira.csssr.io/browse/COM-2267
- стенд: http://fix-com-2267.csssr.cloud/
> fix: COM-2267 1360| Исправил положение картинки на Mindbox

- components/project/Hero/Hero.styles.js
- ссылка на jira: https://jira.csssr.io/browse/COM-2290
- стенд: http://fix-com-2290.csssr.cloud/
> fix: COM-2290 1920| Исправил налезание заголовка на картинку

- static/locales/en/contactUs.json
- static/locales/ru/contactUs.json
- ссылка на jira: COM-2296
- ссылка на jira: COM-2297
- стенд: http://fix-com-2296.csssr.cloud/
> COM-2296: Исправил адрес для Эстонии

- components/contact-us/ContactUs/BookACall/BookACall.styles.js
- components/contact-us/ContactUs/ContactOptions/ContactForm/ContactForm.jsx
- components/contact-us/ContactUs/ContactOptions/ContactForm/ContactForm.styles.js
- components/contact-us/ContactUs/ContactOptions/ContactForm/Dropdown/Dropdown.styles.js
- components/contact-us/ContactUs/ContactOptions/ContactForm/TextField/TextField.styles.js
- components/contact-us/ContactUs/ContactOptions/ContactOptions.styles.js
- components/contact-us/ContactUs/Map/Map.styles.js
- static/icons/mdi_check.svg
- ссылка на jira: COM-2270
- стенд: http://feat-com-2270.csssr.cloud/
> COM-2270: Добавил чекбокс подтверждения

- components/contact-us/ContactUs/Map/Tabs/Tabs.styles.js
- ссылка на jira: COM-2325
- стенд: http://fix-com-2335.csssr.cloud/
> fix: COM-2325 Поправил стили табов в на карте

- components/contact-us/ContactUs/ContactOptions/ContactForm/ContactForm.styles.js
- components/contact-us/ContactUs/ContactOptions/ContactForm/Dropdown/Dropdown.styles.js
- components/contact-us/ContactUs/ContactOptions/ContactForm/TextField/TextField.styles.js
- components/contact-us/ContactUs/ContactOptions/ContactForm/Textarea/Textarea.jsx
- components/contact-us/ContactUs/ContactOptions/ContactForm/Textarea/Textarea.styles.js
- components/contact-us/ContactUs/Map/Tabs/Tabs.styles.js
- static/locales/en/contactUs.json
- ссылка на jira: COM-2316
- стенд: http://fix-com-2316.csssr.cloud/
* https://jira.csssr.io/projects/COM/versions/11906
* стенд: http://release-com-123-contact-us.csssr.cloud
> fix(Contacts): COM-2327

- components/contact-us/ContactUs/ContactOptions/ContactForm/TextField/TextField.styles.js
- ссылка на jira: COM-2323
- стенд: http://fix-com-2323.csssr.cloud/
> COM-2323: Поправил цвет  текста label при ошибке

- components/contact-us/ContactUs/BookACall/BookACall.styles.js
- ссылка на jira: COM-2334
- стенд: http://fix-com-2334.csssr.cloud/
> fix: COM-2334 Поправил текст об успехе бронирования 

- components/contact-us/ContactUs/ContactOptions/ContactOptions.jsx
- components/contact-us/ContactUs/ContactOptions/ContactOptions.styles.js
- ссылка на jira: COM-2342
- стенд: http://feat-com-2342.csssr.cloud/
> COM-2342: Исправил центрирование формы при масштабировании

- components/Header/Menu/Nav/Nav.jsx
- ссылка на jira: COM-1923
- стенд: http://fix-com-1923.csssr.cloud/
> fix COM-1923 : Исправил атрибут rel у ссылок в хедере 

- components/ElearningPlatform/ElearningPlatformContent.jsx
- components/ElearningPlatform/FeatureButton/FeatureButton.jsx
- components/job/CandidateForm/CandidateForm.jsx
- components/job/CandidateForm/CandidateForm.styles.js
- components/jobs/Vacancies/Vacancies.jsx
- components/jobs/Vacancies/Vacancies.styles.js
- components/way-of-work/Development/Development.jsx
- components/way-of-work/Organized/Organized.jsx
- static/locales/en/backEndAndDevops.json
- static/locales/en/coreValues.json
- static/locales/en/express.json
- static/locales/en/industry.json
- static/locales/en/jobs.json
- static/locales/en/main.json
- static/locales/en/mvp.json
- static/locales/en/outsourcingFrontEnd.json
- static/locales/en/project.json
- static/locales/en/technologies.json
- static/locales/en/wayOfWork.json
- ссылка на jira: https://jira.csssr.io/browse/COM-2271
- стенд: http://feat-com-2271.csssr.cloud/
> feat: COM-2271 Обновил информацию на en

- components/contact-us/ContactUs/ContactOptions/ContactForm/TextField/TextField.styles.js
- components/contact-us/ContactUs/ContactOptions/ContactForm/Textarea/Textarea.jsx
- components/contact-us/ContactUs/ContactOptions/ContactForm/Textarea/Textarea.styles.js
- ссылка на jira: COM-2336
- стенд: http://fix-com-2336.csssr.cloud/
> fix: COM-2336: Исправил лишние отступы при вводе символов

- server/index.js
- ссылка на jira: COM-2390
- стенд: http://COM-2390.csssr.cloud/
> COM-2390: fixed robots.txt for test and prod

- components/way-of-work/Development/Development.jsx
- components/way-of-work/Organized/Organized.jsx
- components/way-of-work/Transparency/Transparency.jsx
- ссылка на jira: COM-2426
- стенд: http://COM-2426csssr.cloud/
> COM-2426: leave only one H1 on way-of-work page

- components/contact-us/ContactUs/BookACall/BookACall.jsx
- ссылка на jira: COM-2331
- стенд: http://feat-com-2331.csssr.cloud/
> COM-2331: Добавил анимацию в BookACall

- components/contact-us/ContactUs/BookACall/BookACall.styles.js
- components/contact-us/ContactUs/ContactOptions/ContactOptions.styles.js
- ссылка на jira: COM-2379
- ссылка на jira: COM-2380
- ссылка на jira: COM-2381
- ссылка на jira: COM-2383
- стенд: http://fix-com-2379.csssr.cloud/
> fix: COM-2379, COM-2380, COM-2381, COM-2383 Поправил PP на странице contacts

- components/industry/OurClients/OurClients.styles.js
- components/main/AboutUs/AboutUs.styles.js
- components/main/Card/Card.styles.js
- components/project/TechStack/TechStack.styles.js
- ссылка на jira: COM-2187
- ссылка на jira: COM-2353
- ссылка на jira: COM-2276
- ссылка на jira: COM-2187
- стенд: http://fix-com-2187.csssr.cloud/
> fix: COM-2187, COM-2353, COM-2276, COM-2187 Внес правки по багам в Safari

- static/icons/main/triangle.svg
- ссылка на jira: COM-2253
- стенд: http://COM-2253.csssr.cloud/
> COM-2253: fixes triangle icon shape

- static/locales/en/industry.json
> fix(SEO): COM-2516  Внес правки для alt-текста

- components/Header/Header.jsx
- components/Header/Header.styles.js
- ссылка на jira: COM-2346
- стенд: http://COM-2346.csssr.cloud/
> COM-2346: убрал скрывающийся хедер

- components/contact-us/ContactUs/BookACall/BookACall.styles.js
- components/contact-us/ContactUs/Map/Map.jsx
- components/contact-us/ContactUs/Map/Map.styles.js
- ссылка на jira: COM-2385
- ссылка на jira: COM-2532
> COM-2385, COM-2532: Правки по странице контакты мобильной версии

- components/project/Quote/Quote.styles.js
> fix: COM-2568 Поправил фон на кейсе Флант

- components/main/ab-test/v3/Hero/Hero.jsx
- data/ab-test/main/metaEn.js
> fix: COM-2567 Fix typo

- components/Header/Links/Links.jsx
- add blog link to header on ru locale
- ссылка на jira: COM-2549
> fix(Header): COM-2549 update header links

- components/industry/Greeting/Greeting.styles.js
- ссылка на jira: COM-2446
- стенд: http://fix-com-2446.csssr.cloud/
> fix: COM-2446: Поправил размеры картинок в индустриях

- components/Picture.jsx
- components/job/CandidateForm/CandidateForm.jsx
- components/job/CandidateForm/Vacancy/Vacancy.jsx
- components/job/CandidateForm/VacancyImageAndLinks/VacancyImageAndLinks.jsx
- components/job/CandidateInfoSection/CandidateInfoSection.jsx
- components/job/ContactOptions/ContactOptions.jsx
- components/jobs/Vacancies/Vacancies.jsx
- components/ui-kit/FileField/FileField.jsx
- components/ui-kit/FormStateMessage/FormStateMessage.jsx
- components/ui-kit/TextField/TextField.jsx
- package.json
- yarn.lock
- ссылка на jira: COM-2374
- стенд: http://feat-com-2374.csssr.cloud/
> COM-2374: Добавил data-testid на страницу вакансий

- package.json
- yarn.lock
* https://jira.csssr.io/projects/COM/versions/11949
* стенд: http://release-com-minor-fix.csssr.cloud
> release: COM-minor-fix

- static/locales/en/industry.json
- ссылка на jira: COM-2580
- стенд: http://fix-com-2580.csssr.cloud/
> fix(flant): COM-2580 Исправил количество месяцев в проекте Flant

- e2e-tests/nightwatch/screenshots/base/04_Контакты/аватар(Анастасия_Внученко)/chrome-1200x800.png
- e2e-tests/nightwatch/screenshots/base/04_Контакты/аватар(Анастасия_Игнатенко)/chrome-1200x800.png
- e2e-tests/nightwatch/screenshots/base/04_Контакты/аватар(Виктория_Зубарева)/chrome-1200x800.png
- e2e-tests/nightwatch/screenshots/base/04_Контакты/активный_таб(Россия)/chrome-1200x800.png
- e2e-tests/nightwatch/screenshots/base/04_Контакты/активный_таб(Россия)/chrome-1920x1080.png
- e2e-tests/nightwatch/screenshots/base/04_Контакты/активный_таб(Сингапур)/chrome-1200x800.png
- e2e-tests/nightwatch/screenshots/base/04_Контакты/активный_таб(Эстония)/chrome-1200x800.png
- e2e-tests/nightwatch/screenshots/base/04_Контакты/раскрытый_дропдаун_формы_Что_бы_вы_хотели_обсудить/chrome-1200x800.png
- e2e-tests/nightwatch/tests/04 Контакты.test.js
- Переключение табов с регионами
- Отображение ответственного менеджера в зависимости от региона
- Смена типа запроса
- Отправка заявки для Сингапура
- Отправка заявки для Эстонии
- Отправка заявки для России
- Забронировать звонок для России
- Оправка заявки для HR
- Отсутствие возможности забронировать звонок для HR
- Валидация обязательных полей
- ссылка на jira: https://jira.csssr.io/browse/COM-2537
- стенд: https://csssr.com/ru/contacts
* скриншоты
> COM-2537:E2E тесты_проверка контактов

- components/ContactForm/ContactForm.jsx
- components/ContactModal/ContactModal.jsx
- components/ContactModal/Form/Form.jsx
- components/ContactModal/Form/StatusMessage/StatusMessage.jsx
- components/ui-kit/Checkbox/Checkbox.jsx
- ссылка на jira: COM-2588
- стенд: http://com-2588.csssr.cloud/
> COM-2588: Исправил data-testid 

- components/ContactForm/ContactForm.jsx
- components/ContactModal/Form/Form.jsx
- ссылка на jira: COM-2601
- стенд: http://fix-com-2601.csssr.cloud/
> fix(contact-form): COM-2601 Поправил  data-testid в форме

- components/Footer/DoubleBottom/Addresses/Addresses.jsx
- components/Footer/DoubleBottom/DoubleBottom.jsx
- components/Footer/Footer.jsx
- components/Footer/Nav/LinksList/LinksList.jsx
- components/Footer/PrivacyAndLanguageLinks/PrivacyAndLanguageLinks.jsx
- ссылка на jira: COM-2594
- стенд: http://com-2594.csssr.cloud/
> COM-2594: Добавил data-testid в футер

- components/express/Calculator/CalculatorForm/Checkbox/Checkbox.jsx
- ссылка на jira: COM-2378
- стенд: http://fix-com-2378.csssr.cloud/
> fix(express): COM-2378 Переназначил data-testid на чек-боксах express

- components/contact-us/ContactUs/ContactOptions/ContactForm/ContactForm.jsx
- components/contact-us/ContactUs/ContactOptions/ContactForm/Dropdown/Dropdown.jsx
- components/job/CandidateForm/CandidateForm.jsx
- components/job/CandidateInfoSection/CandidateInfoSection.jsx
- components/job/ContactOptions/ContactOptions.jsx
- components/ui-kit/FileField/FileField.jsx
- components/ui-kit/FormStateMessage/FormStateMessage.jsx
- components/ui-kit/TextField/TextField.jsx
- ссылка на jira: COM-2614
- стенд: http://fix-com-2614.csssr.cloud/
> fix(testId): COM-2614 Исправил data-testid на форме вакансий

- package.json
- yarn.lock
- ссылка на jira: COM-2573
Коммит в самой либе: https://github.com/CSSSR/csssr-amo/commit/f63e31364da49ed43272c1ebfd456064368a7d72
> fix(Calculator): COM-2573 update csssr-amo

- components/jobs/JobsPage.jsx
- components/main/MainPage.jsx
- add error handler for MainPage and JobsPage vacancies request
- ссылка на jira: COM-2079
> fix(requests): COM-2079 vacancies error handling

- components/Footer/Nav/LinksList/LinksList.jsx
- ссылка на jira: COM-2569
- стенд: http://fix-com-2569.csssr.cloud/
> fix(footer): COM-2569 Добавил ссылку на блог в футтер

- components/main/AboutUs/AboutUs.jsx
- components/main/Card/Card.jsx
- components/main/Hero/Hero.jsx
- components/main/Industries/Industries.jsx
- components/main/Projects/Projects.jsx
- components/main/Services/Figures/Figures.jsx
- components/main/Services/OurFeatures/OurFeatures.jsx
- components/main/Services/Services.jsx
- components/main/Vacancies/Vacancies.jsx
- components/main/ab-test/all/Services/OurFeatures/OurFeatures.jsx
- data/main/industries/index.js
- ссылка на jira: COM-2539
- стенд: http://com-2539.csssr.cloud/
> COM-2539: Добавил data-testid на Главную

- components/ContactForm/ContactForm.jsx
- components/ui-kit/FormStateMessage/FormStateMessage.jsx
> fix(testid): COM-2601 Fix success Picture testid

- components/industry/ProjectsItem/ProjectsItem.styles.js
- ссылка на jira: COM-2606
- стенд: http://com-2606.csssr.cloud/
> COM-2606: Изменил отступы в блоке Проекты

- components/service/mvp/Hero/Hero.styles.js
- ссылка на jira: COM-2643
- стенд: http://fix-com-2643.csssr.cloud/
> fix(service): COM-2643 Поправил заголовок в мобильных

- e2e-tests/nightwatch/screenshots/base/13_Professionals_4.0/02_Screenshots/Professionals_4.0_1024_EN/chrome-1024x5700.png
- e2e-tests/nightwatch/screenshots/base/13_Professionals_4.0/02_Screenshots/Professionals_4.0_1024_RU/chrome-1024x5700.png
- e2e-tests/nightwatch/screenshots/base/13_Professionals_4.0/02_Screenshots/Professionals_4.0_1280_EN/chrome-1280x6700.png
- e2e-tests/nightwatch/screenshots/base/13_Professionals_4.0/02_Screenshots/Professionals_4.0_1280_RU/chrome-1280x7300.png
- e2e-tests/nightwatch/screenshots/base/13_Professionals_4.0/02_Screenshots/Professionals_4.0_1360_EN/chrome-1360x7100.png
- e2e-tests/nightwatch/screenshots/base/13_Professionals_4.0/02_Screenshots/Professionals_4.0_1360_RU/chrome-1360x7100.png
- e2e-tests/nightwatch/screenshots/base/13_Professionals_4.0/02_Screenshots/Professionals_4.0_1920_EN/chrome-1920x7200.png
- e2e-tests/nightwatch/screenshots/base/13_Professionals_4.0/02_Screenshots/Professionals_4.0_1920_RU/chrome-1920x7200.png
- e2e-tests/nightwatch/screenshots/base/13_Professionals_4.0/02_Screenshots/Professionals_4.0_360_EN/chrome-360x7400.png
- e2e-tests/nightwatch/screenshots/base/13_Professionals_4.0/02_Screenshots/Professionals_4.0_360_RU/chrome-360x7400.png
- e2e-tests/nightwatch/tests/13 Professionals 4.0/01 Sending request.test.js
- e2e-tests/nightwatch/tests/13 Professionals 4.0/02 Screenshots.test.js
- e2e-tests/nightwatch/tests/13 Professionals 4.0/03 Routs.test.js
- ссылка на jira: COM-__2638__
- стенд: http://__HERE_BRANCH_NAME__.csssr.cloud/
* отправка заявок
* скриншоты
* переход по ссылкам со страницы
> COM-2638-Project-Professional-4.0

- e2e-tests/nightwatch/screenshots/base/11_Technologies/02_Screenshots/Technologies_1024_EN/chrome-1024x5700.png
- e2e-tests/nightwatch/screenshots/base/11_Technologies/02_Screenshots/Technologies_1024_RU/chrome-1024x5700.png
- e2e-tests/nightwatch/screenshots/base/11_Technologies/02_Screenshots/Technologies_1280_EN/chrome-1280x6700.png
- e2e-tests/nightwatch/screenshots/base/11_Technologies/02_Screenshots/Technologies_1280_RU/chrome-1280x7300.png
- e2e-tests/nightwatch/screenshots/base/11_Technologies/02_Screenshots/Technologies_1360_EN/chrome-1360x7100.png
- e2e-tests/nightwatch/screenshots/base/11_Technologies/02_Screenshots/Technologies_1360_RU/chrome-1360x7100.png
- e2e-tests/nightwatch/screenshots/base/11_Technologies/02_Screenshots/Technologies_1920_EN/chrome-1920x7200.png
- e2e-tests/nightwatch/screenshots/base/11_Technologies/02_Screenshots/Technologies_1920_RU/chrome-1920x7200.png
- e2e-tests/nightwatch/screenshots/base/11_Technologies/02_Screenshots/Technologies_360_EN/chrome-360x7400.png
- e2e-tests/nightwatch/screenshots/base/11_Technologies/02_Screenshots/Technologies_360_RU/chrome-360x7400.png
- e2e-tests/nightwatch/tests/11 Technologies/01 Sending request.test.js
- e2e-tests/nightwatch/tests/11 Technologies/02 Screenshots.test.js
- ссылка на jira: COM-__2618__
* тесты на отправку заявок
* тесты скриншотами
> COM-2618-e2e-Tecnologies

- e2e-tests/nightwatch/screenshots/base/00_Header/03_Скриншоты_хеддера_RU/Хеддер_на_1024_RU/chrome-1024x1024.png
- e2e-tests/nightwatch/screenshots/base/00_Header/03_Скриншоты_хеддера_RU/Хеддер_на_1280_RU/chrome-1280x1024.png
- e2e-tests/nightwatch/screenshots/base/00_Header/03_Скриншоты_хеддера_RU/Хеддер_на_1360_RU/chrome-1360x1024.png
- e2e-tests/nightwatch/screenshots/base/00_Header/03_Скриншоты_хеддера_RU/Хеддер_на_1920_RU/chrome-1920x1024.png
- e2e-tests/nightwatch/screenshots/base/00_Header/03_Скриншоты_хеддера_RU/Хеддер_на_странице_вакансий_без_кнопки_связи_1024_RU/chrome-1024x1024.png
- e2e-tests/nightwatch/screenshots/base/00_Header/03_Скриншоты_хеддера_RU/Хеддер_на_странице_вакансий_без_кнопки_связи_1280_RU/chrome-1280x1024.png
- e2e-tests/nightwatch/screenshots/base/00_Header/03_Скриншоты_хеддера_RU/Хеддер_на_странице_вакансий_без_кнопки_связи_1360_RU/chrome-1024x1024.png
- e2e-tests/nightwatch/screenshots/base/00_Header/03_Скриншоты_хеддера_RU/Хеддер_на_странице_вакансий_без_кнопки_связи_1360_RU/chrome-1360x1024.png
- e2e-tests/nightwatch/screenshots/base/00_Header/03_Скриншоты_хеддера_RU/Хеддер_на_странице_вакансий_без_кнопки_связи_1920_RU/chrome-1920x1024.png
- e2e-tests/nightwatch/screenshots/base/00_Header/04_Скриншоты_хеддера_EN/Дропдаун_SERVICES_1024_EN/chrome-1024x1024.png
- e2e-tests/nightwatch/screenshots/base/00_Header/04_Скриншоты_хеддера_EN/Хеддер_на_1024_EN/chrome-1024x1024.png
- e2e-tests/nightwatch/screenshots/base/00_Header/04_Скриншоты_хеддера_EN/Хеддер_на_1280_EN/chrome-1280x1024.png
- e2e-tests/nightwatch/screenshots/base/00_Header/04_Скриншоты_хеддера_EN/Хеддер_на_1360_EN/chrome-1360x1024.png
- e2e-tests/nightwatch/screenshots/base/00_Header/04_Скриншоты_хеддера_EN/Хеддер_на_1920_EN/chrome-1920x1024.png
- e2e-tests/nightwatch/screenshots/base/00_Header/04_Скриншоты_хеддера_EN/Хеддер_на_странице_вакансий_без_кнопки_связи_1024_EN/chrome-1024x1024.png
- e2e-tests/nightwatch/screenshots/base/00_Header/04_Скриншоты_хеддера_EN/Хеддер_на_странице_вакансий_без_кнопки_связи_1280_EN/chrome-1280x1024.png
- e2e-tests/nightwatch/screenshots/base/00_Header/04_Скриншоты_хеддера_EN/Хеддер_на_странице_вакансий_без_кнопки_связи_1360_EN/chrome-1360x1024.png
- e2e-tests/nightwatch/screenshots/base/00_Header/04_Скриншоты_хеддера_EN/Хеддер_на_странице_вакансий_без_кнопки_связи_1920_EN/chrome-1920x1024.png
- e2e-tests/nightwatch/tests/00 Header/01 Роуты для RU.test.js
- e2e-tests/nightwatch/tests/00 Header/02 Роуты для EN.test.js
- e2e-tests/nightwatch/tests/00 Header/03 Скриншоты хеддера RU.test.js
- e2e-tests/nightwatch/tests/00 Header/04 Скриншоты хеддера EN.test.js
- ссылка на jira: COM-__2590__
* обновлены скриншоты
* добавлены тесты на новые разделы
* исправлен метод проверки открытия страницы в новой вкладке
* добавлено ожидание
* заменены селекторы на data-testid
* исправлен стиль описания шагов
> COM-2590-e2e - Header test updates

- components/way-of-work/Greeting/Greeting.styles.js
> fix: COM-2636 Опустил картинку в первом блоке процессы

- components/industry/Greeting/Greeting.styles.js
- components/service/backend-devops/Hero/Hero.styles.js
- ссылка на jira: COM-2589
- ссылка на jira: COM-2648
> COM-2589, COM-2648 Исправил размеры изображений в блоках Hero

- components/ContactForm/ContactForm.jsx
> fix(form): COM-2576 Поправил лишний текст при успешной отправке заявки

- components/ContactModal/Form/StatusMessage/StatusMessage.styles.js
> fix(images): COM-2663 Поправил размер картинки успеха отправки формы

- components/main/Services/Services.styles.js
- components/main/ab-test/all/Services/Services.styles.js
- ссылка на jira: COM-2641
- стенд: http://fix-com-2641.csssr.cloud/
> fix: COM-2641 Поправил заголовок "development" на главной в iOS

- components/way-of-work/Greeting/Greeting.styles.js
> fix(way-of-work): COM-2636 Опустил картинку в первом блоке

- e2e-tests/nightwatch/screenshots/base/05_Footer/видео_в_футере/chrome-1200x800.png
- e2e-tests/nightwatch/screenshots/base/05_Footer/двойной_футер(вторая_часть)/chrome-1920x4000.png
- e2e-tests/nightwatch/screenshots/base/05_Footer/двойной_футер(первая_часть)/chrome-1920x4000.png
- e2e-tests/nightwatch/screenshots/base/05_Footer/карта(увеличен_пин_Эстонии)/chrome-1920x4000.png
- e2e-tests/nightwatch/tests/05 Footer.test.js
- Воспроизведение видео при наведении на лого CSSSR
- Увеличение пинов на карте при наведении на адрес
- Двойной футер
- Кликабельный e-mail под лого
- Кликабельный e-mail под лого на страницах вакансий
- Кликабельные телефоны
- Отображение времени для офисов
- Переключение языка
- Отображение контактной информации в футере
- Отображение иконок социальных сетей в футере
- Отображение ссылок
- Переход по ссылкам
- ссылка на jira: https://jira.csssr.io/browse/COM-2593
- стенд: https://csssr.com/
* https://jira.csssr.io/projects/COM/versions/__HERE_JIRA_VERSION_ID__
* стенд: http://release-__HERE_JIRA_RELEASE_ID__.csssr.cloud
* скриншоты
> COM-2593: E2E тесты_кейсы футера

- e2e-tests/nightwatch/screenshots/base/15_LMS/02_LMS/Custom_Design(выбран_Color)/chrome-1920x1280.png
- e2e-tests/nightwatch/screenshots/base/15_LMS/02_LMS/Custom_Design(выбран_Font)/chrome-1920x1280.png
- e2e-tests/nightwatch/screenshots/base/15_LMS/02_LMS/Custom_Design(выбран_Graphic)/chrome-1920x1280.png
- e2e-tests/nightwatch/screenshots/base/15_LMS/02_LMS/Custom_Design(выбран_Theme)/chrome-1920x1280.png
- e2e-tests/nightwatch/screenshots/base/15_LMS/02_LMS/описание_карточки_Ecosystem_integration/chrome-1920x1280.png
- e2e-tests/nightwatch/screenshots/base/15_LMS/02_LMS/описание_карточки_Payment_Providers_Integration/chrome-1920x1280.png
- e2e-tests/nightwatch/screenshots/base/15_LMS/02_LMS/описание_карточки_Rating_System/chrome-1920x1280.png
- e2e-tests/nightwatch/screenshots/base/15_LMS/02_LMS/описание_карточки_Skill-Based_Learning_System/chrome-1920x1280.png
- e2e-tests/nightwatch/tests/15 LMS/02 LMS.test.js
- Анимация в блоке "Custom Design"
- Отправка заявки через кнопку в блоке "Need more info?"
- Переход на страницу "Our Process"
- Переход на страницу "Technologies"
- Анимация в блоке "Advanced Feature Ideas"
- Отправка заявки через форму связи в конце страницы
- ссылка на jira: https://jira.csssr.io/browse/COM-2597
- стенд: https://csssr.com/
* https://jira.csssr.io/projects/COM/versions/__HERE_JIRA_VERSION_ID__
* стенд: http://release-__HERE_JIRA_RELEASE_ID__.csssr.cloud
* скриншоты
> COM-2597:E2E тесты_кейсы LMS

- e2e-tests/nightwatch/screenshots/base/07_Процессы/прозрачность_(бирюзовый_круг)/chrome-1920x700.png
- e2e-tests/nightwatch/screenshots/base/07_Процессы/прозрачность_(красный_треугольник)/chrome-1920x700.png
- e2e-tests/nightwatch/screenshots/base/07_Процессы/прозрачность_(оранжевый_ромб)/chrome-1920x700.png
- e2e-tests/nightwatch/screenshots/base/07_Процессы/прозрачность_(синяя_дуга)/chrome-1920x700.png
- e2e-tests/nightwatch/tests/07 Процессы.test.js
- ссылка на jira: https://jira.csssr.io/browse/COM-2665
- стенд: https://csssr.com/
* скриншоты
> COM-2665:E2E тесты_проверка страницы Процессы

- components/way-of-work/Greeting/Greeting.styles.js
- ссылка на jira: https://jira.csssr.io/browse/COM-2636
- стенд: http://fix-com-2636.csssr.cloud/
> fix: COM-2636 320: Background position fix

- server/ab/experiments/en-main-page.json
> fix(ab): COM-2707 remove some variants

- components/contact-us/ContactUs/BookACall/BookACall.jsx
- utils/getProfileId.js
- utils/setBookingPossibility.js
> fix(ContactUs): COM-2731 update managers info

- components/Idea/Idea.jsx
- components/Idea/Idea.styles.js
- components/Idea/index.js
- components/OurCases/Hero/Hero.styles.js
- components/OurCases/OurCasesPage.jsx
- components/industry/EcommercePage.jsx
- components/industry/FintechPage.jsx
- components/industry/InformationTechnologyPage.jsx
- components/industry/MediaAndMarketingPage.jsx
- components/project/BrusnikaPage.jsx
- components/project/FlantPage.jsx
- components/project/GazpromNeftPage.jsx
- components/project/MindboxPage.jsx
- components/project/MosOblGazPage.jsx
- components/project/QMarketingPage.jsx
- components/project/S7AirlinesPage.jsx
- data/our-cases/idea.js
- static/icons/our-cases/triangle.svg
- static/locales/en/ourCases.json
- static/locales/ru/ourCases.json
- ссылка на jira: https://jira.csssr.io/browse/COM-2729
https://jira.csssr.io/browse/COM-2728
- стенд: http://feat-com-2729.com.csssr.cloud/
> Add 'Have an idea' block to projects and industries pages

- components/job/CandidateForm/CandidateForm.jsx
- components/job/CandidateInfoSection/CandidateInfoSection.jsx
- components/job/CandidateInfoSection/CandidateInfoSection.styles.js
- components/job/JobPage.jsx
- ссылка на jira: https://jira.csssr.io/browse/COM-2690
- стенд: http://fix-com-2690.csssr.cloud/
> fix: COM-2690 Remove checkbox from candidate form

- components/CookiesPopup/CookiesPopup.styles.js
> fix(CookiesPopup): COM-2764 update styles

- components/Idea/Idea.styles.js
- components/OurCases/DevCases/Case/Case.jsx
- components/OurCases/DevCases/Case/Case.styles.js
- data/our-cases/devCases.js
- static/locales/en/industry.json
- static/locales/en/ourCases.json
- static/locales/ru/ourCases.json
- ссылка на jira: https://jira.csssr.io/browse/COM-2784
https://jira.csssr.io/browse/COM-2782
https://jira.csssr.io/browse/COM-2785
https://jira.csssr.io/browse/COM-2787
- стенд: http://fix-com-2784.com.csssr.cloud/
> fix: COM-2784 Dev cases page fixes

- components/OurCases/DevCases/Case/Case.styles.js
- ссылка на jira: https://jira.csssr.io/browse/COM-2787
- стенд: http://fix-com-2787.com.csssr.cloud/
> fix: COM-2787 Our cases page: reduce hover zone

- components/Card/Card.jsx
- components/industry/Projects/Projects.jsx
- components/industry/ProjectsItem/ProjectsItem.jsx
- components/main/Cases/Cases.jsx
- components/main/Projects/Post/Post.jsx
- components/main/Projects/Projects.jsx
- components/main/Services/Services.jsx
- components/our-cases/Solutions/Solutions.jsx
* https://jira.csssr.io/projects/COM/versions/12102
* стенд: http://release-com-cases-des.csssr.cloud
> feat(tests): COM-2732 update data-testid on main

- components/OurCases/DevCases/DevCases.styles.js
- ссылка на jira: COM-2840
- стенд: http://fix-com-2840.com.csssr.cloud/
> fix: COM-2840 Our cases: heading layout fix

- e2e-tests/nightwatch/screenshots/base/14_S7_Airlines/02_Screenshots/S7_Airlines_1024_EN/chrome-1024x3800.png
- e2e-tests/nightwatch/screenshots/base/14_S7_Airlines/02_Screenshots/S7_Airlines_1024_RU/chrome-1024x3800.png
- e2e-tests/nightwatch/screenshots/base/14_S7_Airlines/02_Screenshots/S7_Airlines_1280_EN/chrome-1280x5300.png
- e2e-tests/nightwatch/screenshots/base/14_S7_Airlines/02_Screenshots/S7_Airlines_1280_RU/chrome-1280x5300.png
- e2e-tests/nightwatch/screenshots/base/14_S7_Airlines/02_Screenshots/S7_Airlines_1360_EN/chrome-1360x5300.png
- e2e-tests/nightwatch/screenshots/base/14_S7_Airlines/02_Screenshots/S7_Airlines_1360_RU/chrome-1360x5300.png
- e2e-tests/nightwatch/screenshots/base/14_S7_Airlines/02_Screenshots/S7_Airlines_1920_EN/chrome-1920x4950.png
- e2e-tests/nightwatch/screenshots/base/14_S7_Airlines/02_Screenshots/S7_Airlines_1920_RU/chrome-1920x4950.png
- e2e-tests/nightwatch/screenshots/base/14_S7_Airlines/02_Screenshots/S7_Airlines_360_EN/chrome-360x4300.png
- e2e-tests/nightwatch/screenshots/base/14_S7_Airlines/02_Screenshots/S7_Airlines_360_RU/chrome-360x4300.png
- e2e-tests/nightwatch/tests/14 S7 Airlines/01 Sending request.test.js
- e2e-tests/nightwatch/tests/14 S7 Airlines/02 Screenshots.test.js
- e2e-tests/nightwatch/tests/14 S7 Airlines/03 Routs.test.js
- e2e-tests/nightwatch/tests/actions/switchLanguage.js
- ссылка на jira: COM-__2640__
- отправка заявок
- скриншоты
- роуты
> COM-2640-e2e-S7project page

- components/Header/Menu/Nav/Nav.jsx
- components/Header/Menu/Nav/Nav.styles.js
- data/headerLinks.js
- static/icons/header/our-projects.svg
- static/locales/en/common.json
- static/locales/ru/common.json
- ссылка на jira: COM-2880
- стенд: http://feat-com-2880.com.csssr.cloud/
> COM-2880: Добавил our-projects в header

- components/Header/Menu/Nav/Nav.styles.js
- components/projects/ProjectsPage.jsx
- data/footerLinks.js
- data/headerLinks.js
- data/main/services.js
- static/locales/en/main.json
> fix: COM-2884 remove DesignLab links

- components/Footer/Nav/LinksList/LinksList.styles.js
- ссылка на jira: COM-2604
- стенд: http://fix-com-2640.com.csssr.cloud/
> COM-2604: Исправил ховеры ссылок в футере на наши .com

- components/ContactModal/Form/StatusMessage/StatusMessage.styles.js
- ссылка на jira: COM-2829
- стенд: http://fix-com-2829.com.csssr.cloud/
> fix: COM-2829 Поправил скролл на сообщении успеха в модалке

- static/locales/en/project.json
- ссылка на jira: COM-2718
- стенд: http://fix-com-2718.com.csssr.cloud/
> fix: COM-2718 Добавил пробел между "of" и "an" в заголовке S7

- components/ContactForm/ContactForm.styles.js
- ссылка на jira: COM-2871
- стенд: http://fix-com-2871.com.csssr.cloud/
> fix: COM-2871: Убрал квадратики на внутренних ссылках в форме контактов

- components/Header/Menu/Nav/Nav.jsx
- components/Header/Menu/Nav/Nav.styles.js
- data/headerLinks.js
- static/icons/header/our-projects.svg
- static/locales/en/common.json
- static/locales/ru/common.json
* https://jira.csssr.io/projects/COM/versions/com-projects-header
* стенд: http://release-com-projects-header.csssr.cloud
> Release: com-projects-header

- e2e-tests/e2e-tools.json
- ссылка на jira: COM-__COM-2869__
Заменила LAUNCH_URL  на продовый для прогона e2e в Дженкинсе
> COM-2869-e2e_LAUNCH_URL-update

- components/ElearningPlatform/ElearningPlatformContent.jsx
- components/ElearningPlatform/ElearningPlatformContent.styles.js
- components/contact-us/ContactUs/BookACall/BookACall.jsx
- components/contact-us/ContactUs/BookACall/BookACall.styles.js
- components/core-values/DetailValue/DetailValue.jsx
- components/core-values/DetailValue/DetailValue.styles.js
- components/core-values/Greeting/Greeting.jsx
- components/core-values/Greeting/Greeting.styles.js
- components/error/Error404Page.jsx
- components/error/ErrorPage.jsx
- components/error/ErrorPage.styles.js
- components/express/Greeting/Greeting.jsx
- components/express/Greeting/Greeting.styles.js
- components/industry/Greeting/Greeting.jsx
- components/industry/Greeting/Greeting.styles.js
- components/job/CandidateForm/VacancyImageAndLinks/VacancyImageAndLinks.jsx
- components/job/CandidateForm/VacancyImageAndLinks/VacancyImageAndLinks.styles.js
- components/jobs-faq/ImageBlock/ImageBlock.styles.js
- components/jobs/Vacancies/Vacancies.styles.js
- components/project/Hero/Hero.styles.js
- components/projects/Hero/Hero.jsx
- components/projects/Hero/Hero.styles.js
- components/service/backend-devops/Hero/Hero.jsx
- components/service/backend-devops/Hero/Hero.styles.js
- components/service/mvp/Hero/Hero.jsx
- components/service/mvp/Hero/Hero.styles.js
- components/service/outsourcing-front-end/Hero/Hero.jsx
- components/service/outsourcing-front-end/Hero/Hero.styles.js
- components/technologies/Hero/Hero.jsx
- components/technologies/Hero/Hero.styles.js
- ссылка на jira: COM-2039
- стенд: http://feat-com-2039.com.csssr.cloud/
- [+] Указаны ревьюеры
- [+] Стенды собрались и работают
- [+] Код работает полностью согласно описанию задачи
- [+] eslint и dev-консоль браузера без ошибок
> feat: [COM-2039]: Preset size to first pictures on page

- components/Footer/DoubleBottom/Addresses/Addresses.styles.js
- ссылка на jira: COM-2122
- стенд: http://com-2122.com.csssr.cloud/
- [+] Указаны ревьюеры
- [+] Код работает полностью согласно описанию задачи
- [+] eslint и dev-консоль браузера без ошибок
> [COM-2122]: Changed adress cursor

- components/main/Vacancies/Vacancies.jsx
- ссылка на jira: COM-2895
- стенд: http://com-2895.com.csssr.cloud/
> COM-2895: Fix vacancies data-testid

- components/contact-us/ContactUs/BookACall/CalendlyBookingButton/CalendlyBookingButton.styles.js
- ссылка на jira: COM-2879
- стенд: http://com-2879.com.csssr.cloud/
- [+] Указаны ревьюеры
- [+] Код работает полностью согласно описанию задачи
- [+] eslint и dev-консоль браузера без ошибок
> [COM-2879]: Changed popup close button

- components/job/CandidateForm/CandidateForm.jsx
- components/job/CandidateForm/CandidateForm.styles.js
- components/job/section-types/TitleAndList/TitleAndList.styles.js
- ссылка на jira: COM-2947
- стенд: http://com-2947.com.csssr.cloud/
> [COM-2947]: Change job page font styles

- components/Layout/Layout.styles.js
- components/job/section-types/TitleAndList/TitleAndList.styles.js
- components/privacy-policy/PrivacyPolicy.styles.js
- ссылка на jira: COM-2498
- стенд: http://com-2498.com.csssr.cloud/
> [COM-2498]: Change list bullet styles

- components/Footer/PrivacyAndLanguageLinks/PrivacyAndLanguageLinks.jsx
- components/Footer/PrivacyAndLanguageLinks/PrivacyAndLanguageLinks.styles.js
- ссылка на jira: COM-2360
- стенд: http://com-2360.com.csssr.cloud/
> [COM-2360]: Add target blank to policy links

- components/projects/Solutions/Solutions.jsx
- components/projects/Solutions/Solutions.styles.js
- ссылка на jira: COM-2898
- стенд: http://com-2898.com.csssr.cloud/
> [COM-2898]: Remove pseudo element from external\internal link

- .github/workflows/run_lighthouse.yml
- lighthouserc.js
> feat(workflows): COM-2800 add lighthouse check

- .github/workflows/run_eslint.yml
- .github/workflows/run_test.yml
> feat(workflow): COM-2899 add tests and eslint checks

- components/Idea/Idea.styles.js
> fix(Idea): COM-2939 add will-change

- .github/pull_request_template.md
> refactor(github): COM-2900 update PR template

- components/design/DevBlock/DevBlock.styles.js
- [x ] PR is directed to the release branch (if there is a release branch, otherwise this item can be removed)
> feat: COM-2960 Fix text wrapping on Design lab

- static/locales/en/design.json
> feat: COM-2960 Added missing dots

- components/Footer/DoubleBottom/DoubleBottom.jsx
- components/Footer/DoubleBottom/DoubleBottom.styles.js
- components/Footer/Footer.jsx
> fix(footer): COM-2934 update DoubleBottom visibility logic

- components/ElearningPlatform/ElearningPlatformContent.jsx
> feat: COM-2355 LMS | Add scroll to section start on feature click

- components/Footer/SocialLinks/SocialLinks.styles.js
* jira release board: https://jira.csssr.io/projects/COM/versions/__HERE_JIRA_VERSION_ID__
* testing: http://release-__HERE_JIRA_RELEASE_ID__.csssr.cloud
> feat: COM-1915 Mobile| Social icons position fix

- components/project/Timeline/Timeline.jsx
- components/project/Timeline/Timeline.styles.js
> fix: COM-3054 Horizontal scroll fix

- components/Footer/PrivacyAndLanguageLinks/PrivacyAndLanguageLinks.styles.js
> fix: COM-2978 Footer links fix

- components/project/P4Team/P4Team.styles.js
> feat: COM-3064 Words break fix

- static/locales/en/project.json
- static/locales/ru/project.json
> feat: COM-3063 Text fix

- static/locales/en/project.json
> feat: COM-3062 Title fix

- components/project/Hero/Hero.styles.js
- components/project/Team/Team.jsx
- components/project/Team/Team.styles.js
- data/project/brusnika/team.js
- data/project/flant/team.js
- data/project/gazprom-neft/team.js
- data/project/mindbox/team.js
- data/project/mosoblgaz/team.js
- data/project/qmarketing/team.js
- data/project/s7airlines/team.js
- static/locales/en/project.json
- static/locales/ru/project.json
* jira release board: https://jira.csssr.io/projects/COM/versions/https://jira.csssr.io/projects/COM/versions/12704
* testing: http://release-com-project-fix.csssr.cloud
> feat: COM-3037 Team composition| Text fix

- components/project/Timeline/Timeline.styles.js
> feat: COM-3069 Ru| text position fix

- components/project/Hero/Hero.styles.js
* jira release board: https://jira.csssr.io/projects/COM/versions/12500
* testing: http://release-com-case-p4.com.csssr.cloud
> feat: COM-3074 P4| Animation hero block fix

- components/project/Hero/Hero.jsx
- components/project/Hero/Hero.styles.js
testing: http://release-com-case-p4.com.csssr.cloud
> feat: COM-3084 P4| Fixed bottom padding in Hero block

- components/project/P4Team/P4Team.styles.js
testing: http://release-com-case-p4.com.csssr.cloud
> feat: COM-3085 P4|subheading margin fix

- components/ContactModal/ContactModal.jsx
> [COM-2991]: Turned off cookies popup closing by click outside

- components/job/CandidateForm/VacancyImageAndLinks/VacancyImageAndLinks.styles.js
> feat: COM-3049 Job page| Image height fix

- static/locales/en/main.json
> feat: COM-3067 En| Replace '&' to 'and'

- components/Footer/Nav/Nav.jsx
- static/locales/ru/common.json
> fix(footer): COM-3116 update ru links

- components/CookiesPopup/CookiesPopup.styles.js
> [COM-3105]: Fixed cookies-popup picture

- components/Footer/PrivacyAndLanguageLinks/PrivacyAndLanguageLinks.jsx
- components/Footer/PrivacyAndLanguageLinks/PrivacyAndLanguageLinks.styles.js
> [COM-3117]: Fixed cookie-policy font weight

- static/icons/header/computer.svg
> [COM-3104]: Modified computer icon svg

- e2e-tests/nightwatch/screenshots/base/01_Main/03_Features/Logo_CSSSR/chrome-1920x1080.png
- e2e-tests/nightwatch/tests/01 Main/03 Features.test.js
Updates test:
* from «CSSSR logo animation» to «Hero block»
**Task**
* link JIRA: https://jira.csssr.io/browse/COM-3000
* stand: https://csssr.com/
* run Jenkins: https://jenkins.csssr.ru/view/e2e-tests/job/csssr-com-nightwatch-e2e/job/e2e-COM-3000/3/console
**For reviewers**
How to review e2e tests: https://github.com/CSSSR/e2e-tools/blob/master/docs/REVIEW.md
> COM-3000: E2E test_updates an irrelevant screenshot of the first screen test

- components/Footer/Nav/Nav.jsx
- components/error/Error404Page.jsx
- data/error/navItems.js
- data/footerLinks.js
- static/locales/en/common.json
> feat: COM-3120 Changed 'Products' to 'Solutions'

- data/footerLinks.js
- static/locales/en/common.json
- static/locales/ru/common.json
> feat: COM-3212 Footer| Fixes in Portfolio column

- pages/404.js
- pages/en/404.js
- pages/en/500.js
- pages/ru/404.js
- pages/ru/500.js
- server/check-sitemap.js
> fix(pages): COM-3197 add separate 404 and 500 pages

- components/Layout/Layout.jsx
- data/error/navItems.js
> [COM-3277]: Hid Discount banner

- static/locales/en/common.json
> feat: COM-3241 Footer| Changed 'Contact us' to 'Contacts'

- components/main/Hero/Hero.jsx
> fix(e2e): COM-3220 add data-testid to Hero

- components/CookiesPopup/CookiesPopup.jsx
> fix(components): COM-3219 update CookiesPopup

- static/locales/en/projects.json
> feat: COM-3151 Projects| Changed '&' to 'and'

- components/Header/Menu/Menu.styles.js
> fix: COM-3268 Removed pointer from header menu items
